[package]
name = "cargo-kas-l2"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-kas-l2"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "8.0.0"
