[package]
name = "kas_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "3.0.0"

[target.'cfg(all(target_arch = "riscv32", target_vendor = "succinct"))'.dependencies]
sp1-zkvm = "5.2.1"