[package]
name = "kas-l2-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.8.2"
solana-sbpf = "0.12.2"
kas-l2-program = { path = "../program" }
kas-l2-vm = { path = "../vm" }
kas-l2-runtime-macros = { path = "../runtime-macros" }
