[package]
name = "kas-l2-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-core = { path = "../core" }
kas-l2-scheduler = { path = "../scheduler" }
crossbeam-utils = "0.8.21"
crossbeam-deque = "0.8.6"
intrusive-collections = "0.9.7"