[package]
name = "kas-l2-runtime-core"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-atomic = { path = "../atomic"}
borsh = {  version = "1.5.7", features = ["derive"] }
crossbeam-utils = "0.8.21"
crossbeam-deque = "0.8.6"
intrusive-collections = "0.9.7"
num_cpus = "1.17.0"